"""Native model-family definitions for LoRA Lens.

The registry deliberately contains data, not UI policy.  A profile describes the
smallest reproducible text-to-image workflow for a model family.  More elaborate
or future workflows are supported by the API-workflow adapter in ``lora_lab``.
"""

from __future__ import annotations


MODEL_PROFILES = {
    "krea2_turbo": {
        "id": "krea2_turbo", "family": "Krea 2", "variant": "Turbo",
        "category": "Photorealistic", "acceleration": "Distilled model",
        "name": "Krea 2 · Turbo", "adapter": "split_single",
        "description": "Fast deployment test for the distilled Krea 2 model.",
        "model_folder": "diffusion_models",
        "model_contains": ["krea2_turbo_fp8_scaled", "krea2_turbo_int8", "krea2_turbo_bf16"],
        "clip_type": "krea2", "clip_contains": ["qwen3vl_4b_fp8_scaled", "qwen3vl_4b_bf16"],
        "vae_contains": ["qwen_image_vae"], "latent": "EmptyLatentImage",
        "steps": 8, "cfg": 1.0, "sampler": "euler", "scheduler": "simple",
        "negative_mode": "zero", "seconds_per_cell_4090": 28,
        "source": "Existing validated Krea 2 workflow",
    },
    "krea2_raw": {
        "id": "krea2_raw", "family": "Krea 2", "variant": "Raw",
        "category": "Photorealistic", "acceleration": "None",
        "name": "Krea 2 · Raw", "adapter": "split_single",
        "description": "Training-base verification with editable full-quality sampling.",
        "model_folder": "diffusion_models", "model_contains": ["krea2_raw_fp8_scaled", "krea2_raw_bf16"],
        "clip_type": "krea2", "clip_contains": ["qwen3vl_4b_fp8_scaled", "qwen3vl_4b_bf16"],
        "vae_contains": ["qwen_image_vae"], "latent": "EmptyLatentImage",
        "steps": 52, "cfg": 3.5, "sampler": "euler", "scheduler": "simple",
        "negative_mode": "encode", "seconds_per_cell_4090": 135,
        "supports_acceleration_lora": True, "source": "Existing validated Krea 2 workflow",
    },
    "flux1_dev": {
        "id": "flux1_dev", "family": "FLUX.1", "variant": "Dev",
        "category": "General purpose", "acceleration": "None",
        "name": "FLUX.1 · Dev", "adapter": "split_dual",
        "description": "Full FLUX.1 Dev workflow. Best quality; comparatively expensive.",
        "model_folder": "diffusion_models", "model_contains": ["flux1-dev", "flux1_dev"],
        "clip_type": "flux", "clip_contains": ["clip_l"],
        "clip_2_contains": ["t5xxl_fp16", "t5xxl_fp8_e4m3fn_scaled", "t5xxl_fp8_e4m3fn"],
        "vae_contains": ["ae.safetensors", "ae"], "latent": "EmptySD3LatentImage",
        "steps": 20, "cfg": 1.0, "sampler": "euler", "scheduler": "simple",
        "negative_mode": "zero", "seconds_per_cell_4090": 75,
        "source": "Official ComfyUI FLUX.1 template",
    },
    "flux1_schnell": {
        "id": "flux1_schnell", "family": "FLUX.1", "variant": "Schnell",
        "category": "General purpose", "acceleration": "Distilled model",
        "name": "FLUX.1 · Schnell", "adapter": "split_dual",
        "description": "Distilled FLUX.1 workflow for rapid checkpoint screening.",
        "model_folder": "diffusion_models", "model_contains": ["flux1-schnell", "flux1_schnell"],
        "clip_type": "flux", "clip_contains": ["clip_l"],
        "clip_2_contains": ["t5xxl_fp8_e4m3fn", "t5xxl_fp16"],
        "vae_contains": ["ae.safetensors", "ae"], "latent": "EmptySD3LatentImage",
        "steps": 4, "cfg": 1.0, "sampler": "euler", "scheduler": "simple",
        "negative_mode": "zero", "seconds_per_cell_4090": 18,
        "source": "Official ComfyUI FLUX.1 template",
    },
    "flux1_krea_dev": {
        "id": "flux1_krea_dev", "family": "FLUX.1", "variant": "Krea Dev",
        "category": "Photorealistic", "acceleration": "None",
        "name": "FLUX.1 · Krea Dev", "adapter": "split_dual",
        "description": "Official FLUX.1 Krea Dev base workflow.",
        "model_folder": "diffusion_models", "model_contains": ["flux1-krea-dev", "flux1_krea_dev"],
        "clip_type": "flux", "clip_contains": ["clip_l"],
        "clip_2_contains": ["t5xxl_fp16", "t5xxl_fp8_e4m3fn_scaled"],
        "vae_contains": ["ae.safetensors", "ae"], "latent": "EmptySD3LatentImage",
        "steps": 20, "cfg": 1.0, "sampler": "euler", "scheduler": "simple",
        "negative_mode": "zero", "seconds_per_cell_4090": 75,
        "source": "Official ComfyUI FLUX.1 Krea Dev template",
    },
    "z_image_base": {
        "id": "z_image_base", "family": "Z-Image", "variant": "Base",
        "category": "Photorealistic", "acceleration": "None",
        "name": "Z-Image · Base", "adapter": "split_single",
        "description": "Undistilled Z-Image base for training and full-quality validation.",
        "model_folder": "diffusion_models", "model_contains": ["z_image_bf16", "z-image-base"],
        "clip_type": "lumina2", "clip_contains": ["qwen_3_4b"],
        "vae_contains": ["ae.safetensors", "ae"], "latent": "EmptySD3LatentImage",
        "model_sampling": {"class_type": "ModelSamplingAuraFlow", "inputs": {"shift": 3.0}},
        "steps": 25, "cfg": 4.0, "sampler": "res_multistep", "scheduler": "simple",
        "negative_mode": "encode", "seconds_per_cell_4090": 80,
        "source": "Official ComfyUI Z-Image Base template",
    },
    "z_image_turbo": {
        "id": "z_image_turbo", "family": "Z-Image", "variant": "Turbo",
        "category": "Photorealistic", "acceleration": "Distilled model",
        "name": "Z-Image · Turbo", "adapter": "split_single",
        "description": "Eight-step distilled Z-Image workflow for low-cost screening.",
        "model_folder": "diffusion_models", "model_contains": ["z_image_turbo", "z-image-turbo"],
        "clip_type": "lumina2", "clip_contains": ["qwen_3_4b"],
        "vae_contains": ["ae.safetensors", "ae"], "latent": "EmptySD3LatentImage",
        "model_sampling": {"class_type": "ModelSamplingAuraFlow", "inputs": {"shift": 3.0}},
        "steps": 8, "cfg": 1.0, "sampler": "res_multistep", "scheduler": "simple",
        "negative_mode": "zero", "seconds_per_cell_4090": 28,
        "source": "Official ComfyUI Z-Image Turbo template",
    },
    "anima_base": {
        "id": "anima_base", "family": "Anima", "variant": "Base",
        "category": "Anime and illustration", "acceleration": "None",
        "name": "Anima · Base", "adapter": "split_single",
        "description": "The recommended Anima training base and identity-LoRA validator.",
        "model_folder": "diffusion_models", "model_contains": ["anima-base-v1.0", "anima_base"],
        "clip_type": "stable_diffusion", "clip_contains": ["qwen_3_06b_base"],
        "vae_contains": ["qwen_image_vae"], "latent": "EmptyLatentImage",
        "steps": 30, "cfg": 4.0, "sampler": "er_sde", "scheduler": "simple",
        "negative_mode": "encode", "seconds_per_cell_4090": 42,
        "source": "Official Anima model card and ComfyUI template",
    },
    "anima_aesthetic": {
        "id": "anima_aesthetic", "family": "Anima", "variant": "Aesthetic",
        "category": "Anime and illustration", "acceleration": "Fine-tuned model",
        "name": "Anima · Aesthetic", "adapter": "split_single",
        "description": "Anima quality-tuned deployment variant.",
        "model_folder": "diffusion_models", "model_contains": ["anima-aesthetic", "anima_aesthetic"],
        "clip_type": "stable_diffusion", "clip_contains": ["qwen_3_06b_base"],
        "vae_contains": ["qwen_image_vae"], "latent": "EmptyLatentImage",
        "steps": 30, "cfg": 4.0, "sampler": "er_sde", "scheduler": "simple",
        "negative_mode": "encode", "seconds_per_cell_4090": 42,
        "source": "Official Anima model card",
    },
    "anima_turbo": {
        "id": "anima_turbo", "family": "Anima", "variant": "Turbo",
        "category": "Anime and illustration", "acceleration": "Distilled model",
        "name": "Anima · Turbo", "adapter": "split_single",
        "description": "Fast distilled Anima deployment workflow.",
        "model_folder": "diffusion_models", "model_contains": ["anima-turbo", "anima_turbo"],
        "clip_type": "stable_diffusion", "clip_contains": ["qwen_3_06b_base"],
        "vae_contains": ["qwen_image_vae"], "latent": "EmptyLatentImage",
        "steps": 8, "cfg": 1.0, "sampler": "euler", "scheduler": "simple",
        "negative_mode": "zero", "seconds_per_cell_4090": 18,
        "source": "Official Anima model card",
    },
}


def public_profiles() -> list[dict]:
    return [dict(profile) for profile in MODEL_PROFILES.values()]
